## LLM configuration
apiKey: "Change me or leave it blank if local endpoint"
url: "api.deepseek.com"
model: "deepseek-chat"
maxConcurrency: 5 # Set how many translation request at the same time. Recommended to leave it at 5 or lower for local
modelParams:
  temperature: 0.2
  top_p: 0.9
  frequency_penalty: 0
  presence_penalty: 0
systemPrompt: |
  Translate Simplified Chinese into English, preserving context and meaning. Keep special characters, including escaped sequences (e.g., \n, \=, <), as they appear. Use direct English for professional titles (Envoy, Doctor, Captain) and traditional English for noble/martial titles (Lord, Master, Hero) and Wuxia terms (Qi, sects, cultivation). Use Pinyin for names only, not titles. Default to gender-neutral terms unless gender is explicit. Refine phrasing for readability while maintaining intent and capitalization. Output only the translation.
glossaryPrompt: |
  #Glossary for Consistent Translations
  Use the translation for exact matches.
  ## Terms
glossaryLines:
  - raw: ゲーム
    result: Game
  - raw: 終了
    result: Exit
  - raw: 主人
    result: Master